### ISSUE TITLE
allow search by "id" in users tab

### ISSUE THREAD

**Issue by bigtweekx** [shayaantx/project_cartographer_admin_server#11]
currently you can only search by username. since we can find out xiuds (which is basically a padded ID) now, its useful to search by ID

**Comment by shayaantx** [comment]
I don't see how you want me to search on this, the xuid is on the relay/master, not the admin db

**Comment by bigtweekx** [comment]
I was referring to the number in the "Id" column 
![image](https://user-images.githubusercontent.com/18296142/70404699-80b6b080-1a00-11ea-9678-3e0e429dcf5a.png)

**Comment by shayaantx** [comment]
done in https://github.com/shayaantx/project_cartographer_admin_server/commit/121b7ec656c772fcb5ec450d7af857dfe9487a35
