### ISSUE TITLE
Mobile support 

### ISSUE THREAD

**Issue by iSupersniper** [shayaantx/project_cartographer_admin_server#14]
When clicking on user or machine boxes to edit, it doesn't work on devices with no mouse input.

an example is tablets or phones with touch support.

**Comment by shayaantx** [comment]
I'd have to rewrite the frontend in some framework that supports mobile automatically, I'm using raw htmls and jquery, for the limited number of people that use this, there really is no point.

If you really want to use in a phone, open the page in desktop mode in chrome app

**Comment by bigtweekx** [comment]
works fine on chrome android as is
