### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by bigtweekx** [shayaantx/project_cartographer_admin_server#2]
Needs to have some sort of alias search function.

ex: search for all aliases of "tweek"

code will find tweek's comp id, and use that to find all user_ids related to that comp.
same with IP

**Comment by shayaantx** [comment]
Believe this was done in https://github.com/shayaantx/project_cartographer_admin_server/commit/01a31196c8e79f9241d126873dfb31ff7e7d804f
