### ISSUE TITLE
Username not filled in properly in resent emails

### ISSUE THREAD

**Issue by General-101** [shayaantx/project_cartographer_admin_server#20]
Username in emails that are resent have '$user_username' instead of the actual name of the user. See attached image as example

![bug2020](https://user-images.githubusercontent.com/23564623/89126192-75d9f000-d4a9-11ea-9e30-97186b5efa54.png)

**Comment by shayaantx** [comment]
fixed here https://github.com/shayaantx/project_cartographer_admin_server/commit/fcc7c78afad324281c9000f0c8689a4e01f9bb77
