### ISSUE TITLE
Username does not update if case is the only difference

### ISSUE THREAD

**Issue by General-101** [shayaantx/project_cartographer_admin_server#21]
A username of "test" will not update if I type "Test"

**Comment by shayaantx** [comment]
so in general we ignore case for strings that are the same - which results in no change. I will remove insensitive case check for just username

**Comment by shayaantx** [comment]
fixed here https://github.com/shayaantx/project_cartographer_admin_server/commit/c5d870719411453cabc788b210f39cbe8d3e288f
