### ISSUE TITLE
add activate all button to "new users"

### ISSUE THREAD

**Issue by bigtweekx** [shayaantx/project_cartographer_admin_server#9]
^

**Comment by shayaantx** [comment]
added in https://github.com/shayaantx/project_cartographer_admin_server/commit/7f081bc39380df2a4d7b420636b6e9ccb55f7af1

**Comment by shayaantx** [comment]
![image](https://user-images.githubusercontent.com/5449086/70408636-db5b0700-1a16-11ea-9a16-477b7b379a4c.png)
